version: '3.3'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - CACHE_URL=redis://redis:6379/1  # Add this if needed for caching
    networks:
      - mynetwork

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
